### ISSUE TITLE
Bug: Malformed Yaml: dependency error @main

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/github-actions#230]
We don't see this error on the `@v15.1.0` release

```
Run ministryofjustice/github-actions/malformed-yaml@main
/usr/bin/docker run --name f1769d719e9022c142e58e2ab7835128dab6_93cfd3 --label 75f176 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cloud-platform-infrastructure/cloud-platform-infrastructure":"/github/workspace" 75f176:9d719e9022c142e58e2ab7835128dab6
/usr/local/bundle/gems/faraday-0.9.0/lib/faraday/options.rb:153:in `new': tried to create Proc object without a block (ArgumentError)
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday/options.rb:153:in `memoized'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday/options.rb:234:in `<class:ProxyOptions>'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday/options.rb:216:in `<module:Faraday>'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday/options.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday.rb:80:in `block in require_libs'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday.rb:79:in `each'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday.rb:79:in `require_libs'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday.rb:240:in `<module:Faraday>'
	from /usr/local/bundle/gems/faraday-0.9.0/lib/faraday.rb:16:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `block in <top (required)>'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `each'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/connection.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/client.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from /reject-malformed-yaml.rb:4:in `<main>'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- octokit (LoadError)
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /reject-malformed-yaml.rb:4:in `<main>'
```

**Comment by jasonBirchall** [comment]
That's a HUGE change from 2.1 to 2.7 😖

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-tools-image/compare/2.1...2.7.0

**Comment by jasonBirchall** [comment]
Straight off the bat, the ruby image is completely gone.

**Comment by jasonBirchall** [comment]
I say we start looking at replacing the malformed-yaml action.

**Comment by jasonBirchall** [comment]
@jaskaransarkaria have you looked at megalinter or superlinter?

**Comment by jasonBirchall** [comment]
Version v16.0.0 (latest right now) will work, but you should be looking to move off this action asap.

**Comment by jasonBirchall** [comment]
As this is fixed for now, I will close this ticket. We won't be maintaining this going forward and the suggestion to move off this action will be suggested in future documentation.
